https://numpy.org/doc/stable/user/index.html
Dökümasyonlara buradan bakabilirsin

# Numpy Array

In [2]:
benim_listem = [20,30,40]

In [3]:
type(benim_listem)

list

In [4]:
import numpy as np

In [5]:
np.array(benim_listem)

array([20, 30, 40])

In [6]:
type(np.array(benim_listem))

numpy.ndarray

In [7]:
# Numpy dizisine çevirdik list elemanını 

In [8]:
matrixListesi = [[10,20,30], [40,50,60],[70,80,90]]

In [9]:
## Burada, list içersinde list oluşturduk. 

In [10]:
matrixListesi[1]

[40, 50, 60]

In [11]:
matrixListesi[1][0]

40

In [12]:
## Burada list'in elemanlarına ulaştık

In [13]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
## np.array() ile list'i dizine çevirebiliyoruz
## Neden Numpy Dizinine çeviiriz?
# Matrix şekilde görünüm elde edebiliyoruz bu da bize veri ile kolay çalışma imkanı sunar
# Matrix'imizin bir satırı veya sutunu referans verme imkanı sunar

Not: Numpy dizileri list'lerden dönüştürmek zorunda değiliz hatırlarsan range()
fonksiyonu ile list oluşturabiliyorduk aynı şekilde numpy dizilerinide farklı methodlarla oluşturabiliriz.

# Arange

In [15]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
# Biz range ile list oluşturabiliyoruz

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Numpy dizilerinde ise biz np.arange ile kendi dizilerimizi oluşturabiliyoruz.

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
## Aynı şekikilde arange de step size elemanı verebiliyoruz.

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Zeros

In [22]:
# Sıfırdan oluşan bir dizin oluşturmak istediğimizde kullanıyorz

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# One

In [25]:
# Birden oluşan bir dizin oluşturmak içiin kullanıyoruz

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace 

## `linspace` Fonksiyonunun Kullanımı

`linspace`, NumPy kütüphanesinde bulunan bir fonksiyondur ve belirli bir aralıkta eşit aralıklarla yerleştirilmiş sayılardan oluşan bir dizi (array) oluşturmak için kullanılır. Özellikle sayısal analiz ve bilimsel hesaplamalarda yaygın olarak kullanılır.

### Söz Dizimi

In [28]:
start = 0
stop = 40

In [29]:
np.linspace(start, stop, num=50, endpoint=True, retstep=True, dtype=None, axis=0)

(array([ 0.        ,  0.81632653,  1.63265306,  2.44897959,  3.26530612,
         4.08163265,  4.89795918,  5.71428571,  6.53061224,  7.34693878,
         8.16326531,  8.97959184,  9.79591837, 10.6122449 , 11.42857143,
        12.24489796, 13.06122449, 13.87755102, 14.69387755, 15.51020408,
        16.32653061, 17.14285714, 17.95918367, 18.7755102 , 19.59183673,
        20.40816327, 21.2244898 , 22.04081633, 22.85714286, 23.67346939,
        24.48979592, 25.30612245, 26.12244898, 26.93877551, 27.75510204,
        28.57142857, 29.3877551 , 30.20408163, 31.02040816, 31.83673469,
        32.65306122, 33.46938776, 34.28571429, 35.10204082, 35.91836735,
        36.73469388, 37.55102041, 38.36734694, 39.18367347, 40.        ]),
 0.8163265306122449)

### Parametreler

- **start:** Oluşturulacak dizinin başlangıç değeri.
- **stop:** Oluşturulacak dizinin bitiş değeri.
- **num (opsiyonel):** Dizi içinde yer alacak olan örnek sayısı (default: 50).
- **endpoint (opsiyonel):** True ise, bitiş değeri dizinin son elemanı olarak dahil edilir; False ise dahil edilmez (default: True).
- **retstep (opsiyonel):** True ise, fonksiyon aynı zamanda örnekler arasındaki adım değerini de döndürür (default: False).
- **dtype (opsiyonel):** Çıktı dizisinin veri tipi (default: None).
- **axis (opsiyonel):** Oluşturulan dizinin yerleştirileceği eksen (default: 0).


In [30]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [31]:
# Gördüğün gibi hepsinin arasında 5 kadar uzaklık var

In [32]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [33]:
# Burada her bir elemanın arasında 4 birimlik mesafe var

In [34]:
np.linspace(0,10,20, retstep = True)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
 0.5263157894736842)

In [35]:
# her eleman arasındaki mesafe  0.5263157894736842 olacak ayarladı topllamda da 10 sayı yaptı

In [36]:
np.linspace(0,10,10, retstep = True)

(array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
         5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ]),
 1.1111111111111112)

# Eye

In [37]:
## Birim matrix oluşturur

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Random

Python'da random kütüphanesi, rastgele sayılar üretmek ve rastgele veri seçimi yapmak için kullanılan bir modüldür. Bu kütüphane, oyun geliştirme, veri analizi ve simülasyon gibi birçok alanda yaygın olarak kullanılı

In [40]:
np.random.randn(4)

array([-1.57218135,  0.43586389, -0.82511276, -0.7607201 ])

In [41]:
## Burada tek boyutlu bir numpy dizisi oluştururur

In [42]:
np.random.randn(4,4)

array([[ 1.47644683, -1.1205145 ,  1.50468002,  0.3751231 ],
       [ 0.77865227,  0.09747463,  1.78327369,  0.03482542],
       [-0.42581488, -1.80206762, -2.40247421, -2.36095734],
       [ 1.69156934,  0.87479609,  0.627997  , -1.07874182]])

In [43]:
# Burda da 4,4 2 boyutlu bir numpy dizisi oluşturduk

In [44]:
np.random.randint(1,10)

9

In [45]:
## İlle de numpy dizisi oluşturmak zorunda değilsin int'de oluşturabiliyorsun 
## randint(1,10) 1'le 10 arasında rastgale bir int üretir ve onu yazdırırır 10 dahil değil

In [46]:
# 1 dahil 10 dahil değil

In [47]:
np.random.randint(1,10,5)

array([8, 3, 2, 1, 2])

In [48]:
# Bu şekilde innt değerlerden oluşan bir numpy disizide oluştrabiliriz

In [49]:
np.random.randint(1,300,5)

array([137, 132,   7, 230,  57])

In [50]:
# Büyükten küçüğe küçükten büyüğe değil tamamen rastgele bir şekilde oluştururr

In [51]:
benim_numpy_dizim = np.arange(30)

In [52]:
benim_numpy_dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
# 30 elemanlı bir dizi olusturduk ve gördüğün gibi bir değişkene atadık

In [54]:
benim_randon_dizim = np.random.randint(0,100,30)

In [55]:
benim_randon_dizim

array([77,  1, 10, 94, 72,  7, 81, 32, 21, 89, 97, 99, 54, 60, 70, 66, 88,
       54, 86, 70, 62, 74, 80, 54,  1, 29, 70, 11, 88, 45])

In [56]:
# 0,100 arasında 30 elemanlı bie dizi oluşturduk

# Numpy Dizi Metodları

In [57]:
numpy_dizi = np.arange(30)

In [58]:
numpy_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
# Elimizde 30 elemanlı bir dizi var Bu dizi methodları neler

In [60]:
numpy_dizi.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [61]:
numpy_dizi.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
# reshape(yeniden şekillendir) ile dizimi matris ifadesine çevirebilirim.

In [63]:
numpy_dizi.reshape(5,5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [64]:
# Bu şelilde yazdığımda hata verecektir çünkü 30 elemanlı biz diyiyi 5'e 5'lik bir matris'e oluşturacağım

In [65]:
numpy_dizi.max()

29

In [66]:
# Bir dizindedi max değeri verri

In [67]:
numpy_dizi.min()

0

In [68]:
# minumum değeri gösteriyor

In [69]:
numpy_dizi.argmax()

29

In [70]:
## max değerin kaçıncı indexde olduğu bilgisini verecektir

In [71]:
numpy_dizi.argmin()

0

In [72]:
# min değerin kaçıncı indexde olduğu bilgisine ulaşacaksın

In [73]:
numpy_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
# reshape(6,5) şeklindeki ifade orginal veriyi değiştirmiyor eğer bu (6,5) bir matris
# şeklinde bir görünüm istiyorsan onun için bir değişkene ataman gerekecek

In [76]:
reshape_dizim = numpy_dizi.reshape(5,6)

In [77]:
reshape_dizim.shape

(5, 6)

In [78]:
# Bu bizim ifademizin şeklini veriyor