In [1]:
import numpy as np

In [2]:
benim_dizim = np.arange(0,15)

In [3]:
benim_dizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benim_dizim[5]

5

In [5]:
# Gördüğün hibi nupy dizilerinde de aynı şekilde intexdeki elemanı çağırabiliriz

In [6]:
benim_dizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
## slicing işlemi aynı listteki gi istediğğin aralıktaki elemanları çağırabiliyorrsun

In [8]:
benim_dizim[3:8] = -5 

In [9]:
benim_dizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
## 3,4,5,6,7 index'leri -5 değeri ile değiştirdi ve orginal dizim'ede etki etti

In [11]:
## Let's make example:

In [12]:
baska_dizi = np.arange(0,24)

In [13]:
baska_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
## Gördüğün gibi yeni bir dizi oluşturduk.

In [23]:
slicing_dizi = baska_dizi[4:9]

In [24]:
slicing_dizi

array([4, 5, 6, 7, 8])

In [25]:
baska_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
## Gördüğün gibi şuan herhangi bir değişiklik yapmadık

In [27]:
# slicing_dizi = 700
# type(slicing_dizi)
# int
## Bu şekilde Numpy diizisini int'e eşitledik fakat biz elemanları 700'e eşitlemek istersek

In [28]:
slicing_dizi[:] = 700

In [30]:
slicing_dizi

array([700, 700, 700, 700, 700])

In [32]:
# Gördüğün gibi Numpy dizimizdeki tüm elemanları 700 değerine eşitliyor

In [34]:
baska_dizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [35]:
# Burada gördüğün gibi slicing_dizi'mi baska_dizi den alıp oluşturmuştum ve slicing_dizi'mde
# değişiklik yaptığımda otamatik olarak başka_dizi üzerinde değişiiklik yapmış oldum

In [36]:
#### Peki ben orginal dizimde değişiklik olsun istemiyorsamm:::

In [37]:
# copy() yani; koyasını oluşturmam gerekiyor.

In [38]:
ornek_dizi = np.arange(24)

In [39]:
ornek_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
ornek_dizi_kopyası = ornek_dizi.copy()

In [45]:
ornek_dizi_kopyası_slicing = ornek_dizi_kopyası[3:6]

In [46]:
ornek_dizi_kopyası_slicing[:] = 800

In [49]:
ornek_dizi_kopyası_slicing

array([800, 800, 800])

In [50]:
ornek_dizi_kopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [51]:
ornek_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
# Burada gördüğün gibi eğer orginal dizide prroblem olsun yada sabit kalsın istiyorsan onun kopyasını oluturuyoruz

## Matrix

In [53]:
benim_listem = [[10,20,30], [20,30,40], [50,60,70]]

In [56]:
benim_matrix_dizisi = np.array(benim_listem)

In [57]:
benim_matrix_dizisi

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 70]])

In [58]:
## np.array ile bir list'i matrix'e çevirebiliyoruz

In [59]:
benim_matrix_dizisi[0]

array([10, 20, 30])

In [60]:
benim_matrix_dizisi[0][1]

20

In [61]:
# Eleman içindeki ir elemana ulaştık

In [62]:
## Numpy Dizi Farkı nedi?

In [63]:
benim_matrix_dizisi[0,1]

20

In [64]:
# Burada gördüğün gibi [1,2] ile dizindeki eleman içindeki elemana uşaşabiliyorsun

In [65]:
benim_matrix_dizisi[1:, 2]

array([40, 70])

In [67]:
benim_matrix_dizisi[0:, 1]

array([20, 30, 60])

In [69]:
benim_matrix_dizisi[2:, 0:]

array([[50, 60, 70]])

In [72]:
benim_matrix_dizisi[1:, 1:]

array([[30, 40],
       [60, 70]])

In [73]:
# 1. satırdan başla 3. satıra kadar(en son satırın) 2. index'ini al diyoruz
# [0:, 1] 0'dan son satıra kadar tüm satırların 1.indexdeki elemanları al
# [2:, 0:] burda 2. satırın tüm elemanlarına ulaşabilirsiniz
# [1:, 1:] buraa 1,2 satırın 1. ve 2. elemanlarını aldırdık

In [74]:
yeni_liste = [[0,1,2,3,4], [5,6,7,8,9], [10,11,12,13,14], [15,16,17,18,19], [20,21,22,23,24]]

In [75]:
yeni_matrix = np.array(yeni_liste)

In [76]:
yeni_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
yeni_matrix[[4,2,1]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [79]:
### [[liste]] Numpy dizisinin b,r diğer özelliğide köşeli parantezlerin içine bir list yazınca
### birden fazla indexdeki elemanları alabiliyoruz

# Operasyonlar

In [82]:
yeni_bir_dizi = np.random.randint(1,100,20)

In [83]:
yeni_bir_dizi

array([82, 26, 67, 31, 58, 52, 43, 68, 29, 84, 22, 48,  7, 62, 90,  7, 23,
       29, 80, 73])

In [84]:
sonuc_dizisi = yeni_bir_dizi > 24

In [85]:
sonuc_dizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False, False,  True,
        True,  True])

In [87]:
### yeni_bir_dizi > 24 bu işlem sana eğer büyükse True değilse False ifadelerini dönen bir list veriyor

In [88]:
yeni_bir_dizi[sonuc_dizisi]

array([82, 26, 67, 31, 58, 52, 43, 68, 29, 84, 48, 62, 90, 29, 80, 73])

In [90]:
## yeni_bir_dizi[sonuc_dizisi] bu şekilde de true olan tüm ifadeleri döner 

In [91]:
yeni_bir_dizi[yeni_bir_dizi>10]

array([82, 26, 67, 31, 58, 52, 43, 68, 29, 84, 22, 48, 62, 90, 23, 29, 80,
       73])

In [92]:
## İlla bir değişkene atamak zorunda deilsin yeni_bir_dizi>10 'u köşeli paranteizn içine yazarak
## kolayca fitreleme işlemi yapabilirsin 

## Dizilerde 4 işlem

In [93]:
son_dizi = np.arange(0,24)

In [94]:
son_dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [96]:
son_dizi + son_dizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [97]:
## Gördüğün dizideki gibi index no larına göre tüm iFAdeleri tek tek toplamam işlemi yapabiliyorlar

In [98]:
son_dizi * son_dizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [99]:
son_dizi - son_dizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [100]:
son_dizi / son_dizi

C:\Users\Samira\Sumeyra\AppData\Local\Temp\ipykernel_6316\2415426220.py:1: RuntimeWarning: invalid value encountered in divide
  son_dizi / son_dizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [101]:
### Bolme işlemide yapabiliyoruz falat list'de 0(sıfır) var işlem hata vermesede uyarı veriyor sana
### 0/0 bu isşlem olmaz çünkü

In [102]:
np.sqrt(son_dizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [103]:
### Burada karakök2ünü alma işlemi yaptık 

In [104]:
np.max(son_dizi)

23

In [105]:
np.min(son_dizi)

0

In [106]:
## max ve min lerinide bu şekilde alabiliyoruz